//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationrRecolte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historique_asscociation
    {
        public int ID_histoAssoc { get; set; }
        public int ID_association { get; set; }
        public Nullable<System.DateTime> DATE_desactive { get; set; }
    
        public virtual association association { get; set; }
    }
}
