//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationrRecolte.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecolteEntities : DbContext
    {
        public RecolteEntities()
            : base("name=RecolteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<association> associations { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<colline> collines { get; set; }
        public virtual DbSet<commune> communes { get; set; }
        public virtual DbSet<employe_association> employe_association { get; set; }
        public virtual DbSet<employe_station_lavage> employe_station_lavage { get; set; }
        public virtual DbSet<historique_asscociation> historique_asscociation { get; set; }
        public virtual DbSet<historique_prix> historique_prix { get; set; }
        public virtual DbSet<historique_station> historique_station { get; set; }
        public virtual DbSet<historique_utilisateur> historique_utilisateur { get; set; }
        public virtual DbSet<profile> profiles { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<qualite> qualites { get; set; }
        public virtual DbSet<recolte> recoltes { get; set; }
        public virtual DbSet<station_lavage> station_lavage { get; set; }
        public virtual DbSet<utilisateur> utilisateurs { get; set; }
        public virtual DbSet<zone> zones { get; set; }
    }
}
